repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v6.0.0"
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: requirements-txt-fixer
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.16.3"
    hooks:
      - id: ruff-format
  - repo: local
    hooks:
      - id: disallow-caps
        name: Disallow improper capitalization
        language: pygrep
        entry: PyBind|Numpy|Cmake|CCache|Github|PyTest
        exclude: .pre-commit-config.yaml
