{% set name = "interpret" %}
{% set version = "0.2.5" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/interpretml/interpret.git
  git_rev: "v{{ version }}"

build:
  noarch: generic
  number: 0
  script: cd python/interpret && {{ PYTHON }} setup.py build && {{ PYTHON }} setup.py install

requirements:
  host:
    - pip
    - python
  run:
    - python
    - interpret-core >={{ version }}
    # Equiv. to required.
    - scikit-learn >=0.18.1
    - numpy >=1.11.1
    - scipy >=0.18.1
    - pandas >=0.19.2
    - joblib >=0.11
    # Equiv. to extras.
    - ipython >=7.4.0
    - ipykernel >=5.1.0
    - plotly >=3.8.1
    - lime >=0.1.1.33
    - SALib >=1.3.3
    - shap >=0.25.5
    - dill >=0.2.5
    - dash >=1.0.0
    - dash_cytoscape >=0.1.1
    - gevent >=1.3.6
    - requests >=2.19.0


test:
  imports:
    - interpret

about:
  home: "https://github.com/interpretml/interpret"
  license: MIT
  license_family: MIT
  license_file:  LICENSE
  summary: "Fit interpretable models. Explain blackbox machine learning."
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - interpretml
